name: Run Autoclaim-test

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 */15 * * *'

concurrency:
  group: 'pythonC'  # 设置唯一的组ID
  cancel-in-progress: true 

jobs:
  Blum:
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 150
    if: 'true'
    env:
      WP_CONFIG: ${{ secrets.WARP_CONFIG }}
      SESSION_CONFIG: ${{ secrets.SESSION_CONFIG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Connect InnerWeb
        run: |
          mkdir app/warp
          cd app/warp
          wget https://github.com/Suyunmeng/pfile/releases/download/public-packages/web.js
          wget ${{ env.WP_CONFIG }}
          chmod +x web.js test.json
          nohup ./web.js -c test.json &

      - name: Install dependencies
        run: |
          cd app/1
          npm install

      - name: Run Blum
        run: |
          cd app/1/src/data
          wget ${{ env.SESSION_CONFIG }}/1/users.txt
          chmod +x users.txt
          node app.cjs  # 运行第一个Python脚本